.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ONECLIENT" "1" "January 2017" "" ""
.
.SH "NAME"
\fBoneclient\fR \- Onedata command line client
.
.SH "SYNOPSIS"
\fBoneclient\fR [\-h|\-\-help] [\-V|\-\-version] [\-u|\-\-unmount] [\-c|\-\-config \fIconfig_path\fR] [\-H|\-\-host \fIhostname\fR] [\-P|\-\-port \fIport\fR] [\-i|\-\-insecure] [\-t|\-\-token \fIaccess_token\fR] [\-l|\-\-log\-dir \fIlog_path\fR] [\-\-buffer\-scheduler\-thread\-count \fIthreads\fR] [\-\-communicator\-thread\-count \fIthreads\fR] [\-\-scheduler\-thread\-count \fIthreads\fR] [\-\-storage\-helper\-thread\-count \fIthreads\fR] [\-\-read\-buffer\-min\-size \fIsize\fR] [\-\-read\-buffer\-max\-size \fIsize\fR] [\-\-read\-buffer\-prefetch\-duration \fIduration\fR] [\-\-write\-buffer\-min\-size \fIsize\fR] [\-\-write\-buffer\-max\-size \fIsize\fR] [\-\-write\-buffer\-flush\-delay \fIdelay\fR] [\-f|\-\-foreground] [\-d|\-\-debug] [\-s|\-\-single\-thread] [\-o|\-\-opt \fImount_options\fR] \fImountpoint\fR
.
.SH "DESCRIPTION"
\fBoneclient\fR provides command line interface to mount Onedata (http://onedata\.org) distributed file system data spaces on local machine using Fuse\.
.
.P
\fBoneclient\fR relies on Fuse (Filesystem in Userspace) library, which enables POSIX access to remote data managed by Onedata platform\. Fuse command line options (\fB\-f\fR, \fB\-d\fR, \fB\-s\fR and \fB\-o\fR) can be passed directly to the \fBoneclient\fR on the command line or in the config file (see oneclient\.conf(5))\.
.
.SH "USAGE"
In order to connect to Onedata services, \fBoneclient\fR needs credentials in the form of access token to authenticate the user remotely on the Oneprovider side\. Access tokens can be generated in the web user interface or using the REST API\.
.
.P
\fBoneclient\fR connects to a specific Oneprovider service selected by the user and specified using \fB\-H\fR or \fB\-\-host\fR option and port using \fB\-P\fR or \fB\-\-port\fR\. Port can be omitted if Oneprovider service is deployed on default port (5555)\.
.
.P
\fBNOTE:\fR If you are connecting to a Onedata provider service, which does not have a globally trusted certificate, you will have to use \fB\-i\fR or \fB\-\-insecure\fR on every \fBoneclient\fR invocation\.
.
.SS "Access tokens"
In order to get an authentication token, login to Onezone web user interface, expand \fBAccess Tokens\fR menu on the left and press \fBCreate new access token\fR\. Copy the generated token and pass it to the \fBoneclient\fR command line options using \fB\-t\fR or \fB\-\-token\fR option\.
.
.P
Additionally, the access token can be specified in the \fBONECLIENT_ACCESS_TOKEN\fR environment variable\.
.
.SS "Mounting spaces"
When \fBoneclient\fR connects successfully to the Oneprovider, the \fB<mountpoint>\fR directory will contain the entire list of user spaces, and all regular command line tools can be used to access and modify the files and directories in there, as long as the permissions allow for\.
.
.SS "Proxy IO and Direct IO modes"
\fBoneclient\fR has a unique feature enabling it to transparently detect whenever it has direct access to storage which is used by some Oneprovider instance managing user space, and in such case redirects all IO operations directly to the storage without going through the Oneprovider service (Direct IO mode)\. This feature is detected by \fBoneclient\fR automatically\.
.
.SH "CONFIGURATION"
Beside the command line configuration options, \fBoneclient\fR reads options from a global configuration file located by default at \fB/usr/local/etc/oneclient\.conf\fR (\fB/etc/oneclient\.conf\fR when installed from a distribution package)\. For details see oneclient\.conf(5)\.
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this help and exit\.
.
.TP
\fB\-V\fR, \fB\-\-version\fR
Show current \fBoneclient\fR version and exit\.
.
.TP
\fB\-u\fR, \fB\-\-unmount\fR
Unmount \fBoneclient\fR and exit\.
.
.TP
\fB\-c <config_path>\fR, \fB\-\-config <config_path>\fR
Specify path to user config file\.
.
.TP
\fB\-H <host>\fR, \fB\-\-host <host>\fR
Specify the hostname of the Oneprovider instance to which the \fBoneclient\fR should connect\.
.
.TP
\fB\-P <port>\fR, \fB\-\-port <port>\fR
Specify the port to which the \fBoneclient\fR should connect on the Oneprovider\.
.
.TP
\fB\-i\fR, \fB\-\-insecure\fR
Disable verification of server certificate, allows to connect to servers without valid certificate\.
.
.TP
\fB\-t <token>\fR, \fB\-\-token <token>\fR
Specify Onedata access token for authentication and authorization\.
.
.TP
\fB\-l <log_path>\fR, \fB\-\-log\-dir <log_path>\fR
Specify custom path for \fBoneclient\fR logs\.
.
.TP
\fB\-\-buffer\-scheduler\-thread\-count <threads>\fR
Specify number of parallel buffer scheduler threads\.
.
.TP
\fB\-\-communicator\-thread\-count <threads>\fR
Specify number of parallel communicator threads\.
.
.TP
\fB\-\-scheduler\-thread\-count <threads>\fR
Specify number of parallel scheduler threads\.
.
.TP
\fB\-\-storage\-helper\-thread\-count <threads>\fR
Specify number of parallel storage helper threads\.
.
.TP
\fB\-\-read\-buffer\-min\-size <size>\fR
Specify minimum size in bytes of in\-memory cache for input data blocks\.
.
.TP
\fB\-\-read\-buffer\-max\-size <size>\fR
Specify maximum size in bytes of in\-memory cache for input data blocks\.
.
.TP
\fB\-\-read\-buffer\-prefetch\-duration <duration>\fR
Specify read ahead period in seconds of in\-memory cache for input data blocks\.
.
.TP
\fB\-\-write\-buffer\-min\-size <size>\fR
Specify minimum size in bytes of in\-memory cache for output data blocks\.
.
.TP
\fB\-\-write\-buffer\-max\-size <size>\fR
Specify maximum size in bytes of in\-memory cache for output data blocks\.
.
.TP
\fB\-\-write\-buffer\-flush\-delay <delay>\fR
Specify idle period in seconds before flush of in\-memory cache for output data blocks\.
.
.TP
\fB\-f\fR, \fB\-\-foreground\fR
Foreground operation (see fuse(8))\.
.
.TP
\fB\-d\fR, \fB\-\-debug\fR
Enable debug mode (implies \fB\-f\fR) (see fuse(8))\.
.
.TP
\fB\-s\fR, \fB\-\-single\-thread\fR
Single\-threaded operation (see fuse(8))\.
.
.TP
\fB\-o <mount_options>\fR, \fB\-\-opt <mount_options>\fR
Pass mount arguments directly to FUSE (see fuse\.mount(8))\.
.
.SH "ENVIRONMENT VARIABLES"
Some options in the config file can be overriden using environment variables, whose names are capitalized version of the config options\. The available environment variables are:
.
.TP
\fBONECLIENT_CONFIG\fR
Allows to specify path to user config file\.
.
.TP
\fBONECLIENT_PROVIDER_HOST\fR
Allows to specify the Oneprovider host to which the \fBoneclient\fR will connect\.
.
.TP
\fBONECLIENT_PROVIDER_PORT\fR
Allows to specify Oneprovider port, to which \fBoneclient\fR will connect (default: 5555)\.
.
.TP
\fBONECLIENT_INSECURE\fR
If set to \fB1\fR, disables verification of server certificate and allows to connect to servers without valid certificate\. (default: 0)\.
.
.TP
\fBONECLIENT_ACCESS_TOKEN\fR
Allows to specify Onedata access token for authentication and authorization\.
.
.TP
\fBONECLIENT_LOG_DIR\fR
Allows to specify the log directory for \fBoneclient\fR (default: /tmp)\.
.
.TP
\fBONECLIENT_FUSE_FOREGROUND\fR
If set to \fB1\fR, \fBoneclient\fR will run in foreground mode (default: 0)\.
.
.TP
\fBONECLIENT_FUSE_DEBUG\fR
If set to \fB1\fR, \fBoneclient\fR will run in debug mode (default: 0)\.
.
.TP
\fBONECLIENT_FUSE_SINGLE_THREAD\fR
If set to \fB1\fR, \fBoneclient\fR will run in single thread mode (default: 0)\.
.
.TP
\fBONECLIENT_MOUNTPOINT\fR
Allows to specify default mountpoint for \fBoneclient\fR\.
.
.SH "EXAMPLES"
In order to simply mount your spaces into some local folder use the following command:
.
.P
\fBoneclient \-H onedata\.org \-t <ACCESS_TOKEN> ~/mnt/onedata\fR
.
.P
Connect without validating server certificate and pass token in environment variable:
.
.P
\fBexport ONECLIENT_INSECURE=1\fR
.
.P
\fBexport ONECLIENT_ACCESS_TOKEN=<ACCESS_TOKEN>\fR
.
.P
\fBexport ONECLIENT_PROVIDER_HOST=<ONEPROVIDER_HOST>\fR
.
.P
\fBoneclient ~/mnt/onedata\fR
.
.P
To unmount Onedata spaces use \fBoneclient\fR:
.
.P
\fBoneclient \-u ~/mnt/onedata\fR
.
.P
or using Fuse:
.
.P
\fBfusermount \-u ~/mnt/onedata\fR
.
.SH "COPYRIGHT"
Copyright (C) 2014\-2017, Academic Computer Centre CYFRONET AGH, Krakow, Poland\. Released under the Apache 2\.0 license\.
.
.SH "SEE ALSO"
oneclient\.conf(5), fuse(8), fuse\.mount(8)
