# Used when specific branch for given repo does not exist.
default: develop

branches:
  # Specification of branches from which artifacts will be pulled.
  oz-worker: feature/VFS-12098-test-couchbase-upgrade-to-6.x-from-4.1
  op-worker: feature/VFS-12098-test-couchbase-upgrade-to-6.x-from-4.1
  onepanel: feature/VFS-12098-test-couchbase-upgrade-to-6.x-from-4.1
  cluster-manager: feature/VFS-12098-test-couchbase-upgrade-to-6.x-from-4.1
  oneclient: current_branch
