.TH "CMakeLists.txt" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMakeLists.txt \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcmake_minimum_required\fP (\fBVERSION\fP 2\&.8\&.0) project(VeilClient) include(ExternalProject) set(VeilClient_VERSION_MAJOR 0) set(VeilClient_VERSION_MINOR 1) set(VeilClient_VERSION_PATCH 0) set(VeilClient_VERSION $(VeilClient_VERSION_MAJOR)\&.$(VeilClient_VERSION_MINOR)\&.$(VeilClient_VERSION_PATCH)) set(CONFIG_DIR'etc') set(BIN_DIR'bin') set(LIB_DIR'lib') set(CMAKE_MODULE_PATH $"
.br
.ti -1c
.RI "\fBconfigure_file\fP ('${PROJECT_SOURCE_DIR}/include/veilConfig\&.h\&.in''${PROJECT_BINARY_DIR}/veilConfig\&.h') set(GLOG_PREFIX'src/google-glog') set(YAML_CPP_PREFIX'src/yaml-cpp') include_directories($"
.br
.ti -1c
.RI "include \fBinclude_directories\fP (${PROJECT_SOURCE_DIR}/include/fuse) include_directories($"
.br
.ti -1c
.RI "src \fBmessage\fP (STATUS'Checking for FUSE\&.\&.\&.') find_package(FUSE REQUIRED) \fBinclude_directories\fP($"
.br
.ti -1c
.RI "\fBmessage\fP (STATUS'Checking for Protobuf\&.\&.\&.') find_package(Protobuf REQUIRED) \fBinclude_directories\fP($"
.br
.ti -1c
.RI "\fBmessage\fP (STATUS'Checking for pthreads\&.\&.\&.') find_package(Threads REQUIRED) message(STATUS'Checking for Git\&.\&.\&.') find_package(Git REQUIRED) message(STATUS'Checking for OpenSSL\&.\&.\&.') find_package(OpenSSL REQUIRED) \fBinclude_directories\fP($"
.br
.ti -1c
.RI "\fBmessage\fP (STATUS'Pulling submodules using git\&.\&.\&.') execute_process(COMMAND $"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "cmake_minimum_required (\fBVERSION\fP 2\&.8\&.0)"

.SS "configure_file ('${PROJECT_SOURCE_DIR}/include/veilConfig\&.h\&.in''${PROJECT_BINARY_DIR}/veilConfig\&.h')"

.SS "include_directories (${PROJECT_SOURCE_DIR}/include/)"

.SS "src message (STATUS'Checking for FUSE\&.\&.\&.')"

.SS "message (STATUS'Checking for Protobuf\&.\&.\&.')"

.SS "message (STATUS'Checking for pthreads\&.\&.\&.')"

.SS "message (STATUS'Pulling submodules using git\&.\&.\&.')"

.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
