.TH "include/fuse/communicationHandler.hh" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/fuse/communicationHandler.hh \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCommunicationHandler\fP"
.br
.RI "\fIThe \fBCommunicationHandler\fP class\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Beata Skiba 
.PP
Rafal Slota 
.RE
.PP
\fBCopyright:\fP
.RS 4
(C) 2013 ACK CYFRONET AGH 
.PP
This software is released under the MIT license cited in 'LICENSE\&.txt' 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
