.TH "include/fuse/config.hh" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/fuse/config.hh \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConfig\fP"
.br
.RI "\fIThe \fBConfig\fP singleton\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCLUSTER_HOSTNAME_OPT\fP   'cluster_hostname'"
.br
.RI "\fI\fBConfig\fP option names\&. \fP"
.ti -1c
.RI "#define \fBCLUSTER_PORT_OPT\fP   'cluster_port'"
.br
.ti -1c
.RI "#define \fBLOG_DIR_OPT\fP   'log_dir'"
.br
.ti -1c
.RI "#define \fBPEER_CERTIFICATE_FILE_OPT\fP   'peer_certificate_file'"
.br
.ti -1c
.RI "#define \fBENABLE_ATTR_CACHE_OPT\fP   'enable_attr_cache'"
.br
.ti -1c
.RI "#define \fBATTR_CACHE_EXPIRATION_TIME_OPT\fP   'attr_cache_expiration_time'"
.br
.ti -1c
.RI "#define \fBENABLE_LOCATION_CACHE_OPT\fP   'enable_location_cache'"
.br
.ti -1c
.RI "#define \fBENABLE_ENV_OPTION_OVERRIDE\fP   'enable_env_option_override'"
.br
.ti -1c
.RI "#define \fBFUSE_ID_OPT\fP   'fuse_id'"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Rafal Slota 
.RE
.PP
\fBCopyright:\fP
.RS 4
(C) 2013 ACK CYFRONET AGH 
.PP
This software is released under the MIT license cited in 'LICENSE\&.txt' 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define ATTR_CACHE_EXPIRATION_TIME_OPT   'attr_cache_expiration_time'"

.SS "#define CLUSTER_HOSTNAME_OPT   'cluster_hostname'"

.PP
\fBConfig\fP option names\&. 
.SS "#define CLUSTER_PORT_OPT   'cluster_port'"

.SS "#define ENABLE_ATTR_CACHE_OPT   'enable_attr_cache'"

.SS "#define ENABLE_ENV_OPTION_OVERRIDE   'enable_env_option_override'"

.SS "#define ENABLE_LOCATION_CACHE_OPT   'enable_location_cache'"

.SS "#define FUSE_ID_OPT   'fuse_id'"

.SS "#define LOG_DIR_OPT   'log_dir'"

.SS "#define PEER_CERTIFICATE_FILE_OPT   'peer_certificate_file'"

.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
