.TH "src/helpers/directIOHelper.cc" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/helpers/directIOHelper.cc \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFUSE_USE_VERSION\fP   29"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBfree_path\fP (const char *path)"
.br
.ti -1c
.RI "const char * \fBget_full_path\fP (const char *path)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static char \fBroot_path\fP [PATH_MAX]"
.br
.ti -1c
.RI "static int \fBroot_path_len\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Beata Skiba 
.RE
.PP
\fBCopyright:\fP
.RS 4
(C) 2013 ACK CYFRONET AGH 
.PP
This software is released under the MIT license cited in 'LICENSE\&.txt' 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define FUSE_USE_VERSION   29"

.SH "Function Documentation"
.PP 
.SS "static void free_path (const char *path)\fC [static]\fP"

.SS "const char* get_full_path (const char *path)"

.SH "Variable Documentation"
.PP 
.SS "char root_path[PATH_MAX]\fC [static]\fP"

.SS "int root_path_len\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
