.TH "src/fuse/fslogicProxy.cc" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fuse/fslogicProxy.cc \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFUSE_ID\fP   'abc'"
.br
.ti -1c
.RI "#define \fBGET_FILE_ATTR\fP   'getfileattr'"
.br
.ti -1c
.RI "#define \fBGET_FILE_LOCATION\fP   'getfilelocation'"
.br
.ti -1c
.RI "#define \fBGET_NEW_FILE_LOCATION\fP   'getnewfilelocation'"
.br
.ti -1c
.RI "#define \fBRENEW_FILE_LOCATION\fP   'renewfilelocation'"
.br
.ti -1c
.RI "#define \fBGET_FILE_CHILDREN\fP   'getfilechildren'"
.br
.ti -1c
.RI "#define \fBFILE_CHILDREN\fP   'filechildren'"
.br
.ti -1c
.RI "#define \fBFILE_ATTR\fP   'fileattr'"
.br
.ti -1c
.RI "#define \fBFILE_LOCATION\fP   'filelocation'"
.br
.ti -1c
.RI "#define \fBCREATE_DIR\fP   'createdir'"
.br
.ti -1c
.RI "#define \fBDELETE_FILE\fP   'deletefile'"
.br
.ti -1c
.RI "#define \fBFILE_NOT_USED\fP   'filenotused'"
.br
.ti -1c
.RI "#define \fBRENAME_FILE\fP   'renamefile'"
.br
.ti -1c
.RI "#define \fBCHANGE_FILE_PERMS\fP   'changefileperms'"
.br
.ti -1c
.RI "#define \fBFILE_LOCATION_VALIDITY\fP   'filelocationvalidity'"
.br
.ti -1c
.RI "#define \fBFUSE_MESSAGE\fP   'fusemessage'"
.br
.ti -1c
.RI "#define \fBATOM\fP   'atom'"
.br
.ti -1c
.RI "#define \fBFSLOGIC\fP   'fslogic'"
.br
.ti -1c
.RI "#define \fBNOT_ALLOWED\fP   'not_allowed'"
.br
.ti -1c
.RI "#define \fBOK\fP   'ok'"
.br
.ti -1c
.RI "#define \fBACTION_FAILED\fP   'action_failed'"
.br
.ti -1c
.RI "#define \fBHOST\fP   '127\&.0\&.0\&.1'"
.br
.ti -1c
.RI "#define \fBPORT\fP   5555"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Beata Skiba 
.PP
Rafal Slota 
.RE
.PP
\fBCopyright:\fP
.RS 4
(C) 2013 ACK CYFRONET AGH 
.PP
This software is released under the MIT license cited in 'LICENSE\&.txt' 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define ACTION_FAILED   'action_failed'"

.SS "#define ATOM   'atom'"

.SS "#define CHANGE_FILE_PERMS   'changefileperms'"

.SS "#define CREATE_DIR   'createdir'"

.SS "#define DELETE_FILE   'deletefile'"

.SS "#define FILE_ATTR   'fileattr'"

.SS "#define FILE_CHILDREN   'filechildren'"

.SS "#define FILE_LOCATION   'filelocation'"

.SS "#define FILE_LOCATION_VALIDITY   'filelocationvalidity'"

.SS "#define FILE_NOT_USED   'filenotused'"

.SS "#define FSLOGIC   'fslogic'"

.SS "#define FUSE_ID   'abc'"

.SS "#define FUSE_MESSAGE   'fusemessage'"

.SS "#define GET_FILE_ATTR   'getfileattr'"

.SS "#define GET_FILE_CHILDREN   'getfilechildren'"

.SS "#define GET_FILE_LOCATION   'getfilelocation'"

.SS "#define GET_NEW_FILE_LOCATION   'getnewfilelocation'"

.SS "#define HOST   '127\&.0\&.0\&.1'"

.SS "#define NOT_ALLOWED   'not_allowed'"

.SS "#define OK   'ok'"

.SS "#define PORT   5555"

.SS "#define RENAME_FILE   'renamefile'"

.SS "#define RENEW_FILE_LOCATION   'renewfilelocation'"

.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
