.TH "ISchedulable" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ISchedulable \- 
.PP
The \fBISchedulable\fP interface\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBFslogicProxy\fP, \fBMetaCache\fP, and \fBStorageMapper\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBTaskID\fP { \fBTASK_CLEAR_FILE_ATTR\fP, \fBTASK_SEND_FILE_NOT_USED\fP, \fBTASK_RENEW_LOCATION_MAPPING\fP, \fBTASK_REMOVE_EXPIRED_LOCATON_MAPPING\fP, \fBTASK_LAST_ID\fP }"
.br
.RI "\fIThe TaskID enum\&. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBISchedulable\fP ()"
.br
.ti -1c
.RI "virtual \fB~ISchedulable\fP ()"
.br
.RI "\fIInterface destructor\&. \fP"
.ti -1c
.RI "virtual bool \fBrunTask\fP (\fBTaskID\fP taskId, string arg0, string arg1, string arg3)=0"
.br
.RI "\fICallback which are called by \fBJobScheduler\fP when requested\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBISchedulable\fP interface\&. 

Deriving from this interface gives possibility to schedule and run async, delayed tasks using \fBJobScheduler\fP\&. 
.PP
\fBSee Also:\fP
.RS 4
\fBJobScheduler::addTask\fP 
.RE
.PP

.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBISchedulable::TaskID\fP"

.PP
The TaskID enum\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITASK_CLEAR_FILE_ATTR \fP\fP
.TP
\fB\fITASK_SEND_FILE_NOT_USED \fP\fP
.TP
\fB\fITASK_RENEW_LOCATION_MAPPING \fP\fP
.TP
\fB\fITASK_REMOVE_EXPIRED_LOCATON_MAPPING \fP\fP
.TP
\fB\fITASK_LAST_ID \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ISchedulable::ISchedulable ()"

.SS "ISchedulable::~ISchedulable ()\fC [virtual]\fP"

.PP
Interface destructor\&. Deletes from \fBJobScheduler\fP used by \fBVeilFS\fP all tasks that were registered by this object\&.
.PP
\fBSee Also:\fP
.RS 4
\fBVeilFS::getScheduler\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "virtual bool ISchedulable::runTask (\fBTaskID\fPtaskId, stringarg0, stringarg1, stringarg3)\fC [pure virtual]\fP"

.PP
Callback which are called by \fBJobScheduler\fP when requested\&. \fBSee Also:\fP
.RS 4
\fBJobScheduler\fP 
.RE
.PP

.PP
Implemented in \fBStorageMapper\fP, \fBFslogicProxy\fP, and \fBMetaCache\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
