.TH "IStorageHelper" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IStorageHelper \- 
.PP
The \fBIStorageHelper\fP interface\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDirectIOHelper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IStorageHelper\fP ()"
.br
.ti -1c
.RI "virtual int \fBsh_getattr\fP (const char *path, struct stat *stbuf)=0"
.br
.ti -1c
.RI "virtual int \fBsh_access\fP (const char *path, int mask)=0"
.br
.ti -1c
.RI "virtual int \fBsh_readlink\fP (const char *path, char *buf, size_t size)=0"
.br
.ti -1c
.RI "virtual int \fBsh_readdir\fP (const char *path, void *buf, fuse_fill_dir_t filler, off_t offset, struct fuse_file_info *fi)=0"
.br
.ti -1c
.RI "virtual int \fBsh_mknod\fP (const char *path, mode_t mode, dev_t rdev)=0"
.br
.ti -1c
.RI "virtual int \fBsh_mkdir\fP (const char *path, mode_t mode)=0"
.br
.ti -1c
.RI "virtual int \fBsh_unlink\fP (const char *path)=0"
.br
.ti -1c
.RI "virtual int \fBsh_rmdir\fP (const char *path)=0"
.br
.ti -1c
.RI "virtual int \fBsh_symlink\fP (const char *from, const char *to)=0"
.br
.ti -1c
.RI "virtual int \fBsh_rename\fP (const char *from, const char *to)=0"
.br
.ti -1c
.RI "virtual int \fBsh_link\fP (const char *from, const char *to)=0"
.br
.ti -1c
.RI "virtual int \fBsh_chmod\fP (const char *path, mode_t mode)=0"
.br
.ti -1c
.RI "virtual int \fBsh_chown\fP (const char *path, uid_t uid, gid_t gid)=0"
.br
.ti -1c
.RI "virtual int \fBsh_truncate\fP (const char *path, off_t size)=0"
.br
.ti -1c
.RI "virtual int \fBsh_open\fP (const char *path, struct fuse_file_info *fi)=0"
.br
.ti -1c
.RI "virtual int \fBsh_read\fP (const char *path, char *buf, size_t size, off_t offset, struct fuse_file_info *fi)=0"
.br
.ti -1c
.RI "virtual int \fBsh_write\fP (const char *path, const char *buf, size_t size, off_t offset, struct fuse_file_info *fi)=0"
.br
.ti -1c
.RI "virtual int \fBsh_statfs\fP (const char *path, struct statvfs *stbuf)=0"
.br
.ti -1c
.RI "virtual int \fBsh_release\fP (const char *path, struct fuse_file_info *fi)=0"
.br
.ti -1c
.RI "virtual int \fBsh_fsync\fP (const char *path, int isdatasync, struct fuse_file_info *fi)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBIStorageHelper\fP interface\&. 

Base class of all storage helpers\&. Unifies their interface\&. All callback have their equivalent in FUSE API and should be used in that matter\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IStorageHelper::~IStorageHelper ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual int IStorageHelper::sh_access (const char *path, intmask)\fC [pure virtual]\fP"

.PP
Implemented in \fBDirectIOHelper\fP\&.
.SS "virtual int IStorageHelper::sh_chmod (const char *path, mode_tmode)\fC [pure virtual]\fP"

.PP
Implemented in \fBDirectIOHelper\fP\&.
.SS "virtual int IStorageHelper::sh_chown (const char *path, uid_tuid, gid_tgid)\fC [pure virtual]\fP"

.PP
Implemented in \fBDirectIOHelper\fP\&.
.SS "virtual int IStorageHelper::sh_fsync (const char *path, intisdatasync, struct fuse_file_info *fi)\fC [pure virtual]\fP"

.PP
Implemented in \fBDirectIOHelper\fP\&.
.SS "virtual int IStorageHelper::sh_getattr (const char *path, struct stat *stbuf)\fC [pure virtual]\fP"

.PP
Implemented in \fBDirectIOHelper\fP\&.
.SS "virtual int IStorageHelper::sh_link (const char *from, const char *to)\fC [pure virtual]\fP"

.PP
Implemented in \fBDirectIOHelper\fP\&.
.SS "virtual int IStorageHelper::sh_mkdir (const char *path, mode_tmode)\fC [pure virtual]\fP"

.PP
Implemented in \fBDirectIOHelper\fP\&.
.SS "virtual int IStorageHelper::sh_mknod (const char *path, mode_tmode, dev_trdev)\fC [pure virtual]\fP"

.PP
Implemented in \fBDirectIOHelper\fP\&.
.SS "virtual int IStorageHelper::sh_open (const char *path, struct fuse_file_info *fi)\fC [pure virtual]\fP"

.PP
Implemented in \fBDirectIOHelper\fP\&.
.SS "virtual int IStorageHelper::sh_read (const char *path, char *buf, size_tsize, off_toffset, struct fuse_file_info *fi)\fC [pure virtual]\fP"

.PP
Implemented in \fBDirectIOHelper\fP\&.
.SS "virtual int IStorageHelper::sh_readdir (const char *path, void *buf, fuse_fill_dir_tfiller, off_toffset, struct fuse_file_info *fi)\fC [pure virtual]\fP"

.PP
Implemented in \fBDirectIOHelper\fP\&.
.SS "virtual int IStorageHelper::sh_readlink (const char *path, char *buf, size_tsize)\fC [pure virtual]\fP"

.PP
Implemented in \fBDirectIOHelper\fP\&.
.SS "virtual int IStorageHelper::sh_release (const char *path, struct fuse_file_info *fi)\fC [pure virtual]\fP"

.PP
Implemented in \fBDirectIOHelper\fP\&.
.SS "virtual int IStorageHelper::sh_rename (const char *from, const char *to)\fC [pure virtual]\fP"

.PP
Implemented in \fBDirectIOHelper\fP\&.
.SS "virtual int IStorageHelper::sh_rmdir (const char *path)\fC [pure virtual]\fP"

.PP
Implemented in \fBDirectIOHelper\fP\&.
.SS "virtual int IStorageHelper::sh_statfs (const char *path, struct statvfs *stbuf)\fC [pure virtual]\fP"

.PP
Implemented in \fBDirectIOHelper\fP\&.
.SS "virtual int IStorageHelper::sh_symlink (const char *from, const char *to)\fC [pure virtual]\fP"

.PP
Implemented in \fBDirectIOHelper\fP\&.
.SS "virtual int IStorageHelper::sh_truncate (const char *path, off_tsize)\fC [pure virtual]\fP"

.PP
Implemented in \fBDirectIOHelper\fP\&.
.SS "virtual int IStorageHelper::sh_unlink (const char *path)\fC [pure virtual]\fP"

.PP
Implemented in \fBDirectIOHelper\fP\&.
.SS "virtual int IStorageHelper::sh_write (const char *path, const char *buf, size_tsize, off_toffset, struct fuse_file_info *fi)\fC [pure virtual]\fP"

.PP
Implemented in \fBDirectIOHelper\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
