.TH "Job" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Job \- 
.PP
The \fBJob\fP struct Used by \fBJobScheduler\fP to describe scheduled tasks\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJob\fP (time_t \fBwhen\fP, \fBISchedulable\fP *\fBsubject\fP, \fBISchedulable::TaskID\fP \fBtask\fP, string \fBarg0\fP, string \fBarg1\fP='', string \fBarg2\fP='')"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBJob\fP &other) const "
.br
.RI "\fICompare operator for priority queue\&. \fP"
.ti -1c
.RI "bool \fBoperator==\fP (const \fBJob\fP &other) const "
.br
.RI "\fICompares equal all fields excpet \fBJob::when\fP\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "time_t \fBwhen\fP"
.br
.RI "\fITime when \fBJob\fP should be processed\&. \fP"
.ti -1c
.RI "\fBISchedulable\fP * \fBsubject\fP"
.br
.RI "\fIPointer to object being context of \fBJob\fP execution\&. \fP"
.ti -1c
.RI "\fBISchedulable::TaskID\fP \fBtask\fP"
.br
.RI "\fIID of task\&. \fP"
.ti -1c
.RI "string \fBarg0\fP"
.br
.RI "\fITask's first argument\&. \fP"
.ti -1c
.RI "string \fBarg1\fP"
.br
.RI "\fITask's second argument\&. \fP"
.ti -1c
.RI "string \fBarg2\fP"
.br
.RI "\fITask's third argument\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The \fBJob\fP struct Used by \fBJobScheduler\fP to describe scheduled tasks\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Job::Job (time_twhen, \fBISchedulable\fP *subject, \fBISchedulable::TaskID\fPtask, stringarg0, stringarg1 = \fC''\fP, stringarg2 = \fC''\fP)"

.SH "Member Function Documentation"
.PP 
.SS "bool Job::operator< (const \fBJob\fP &other) const"

.PP
Compare operator for priority queue\&. It compares tasks by it's \fBJob::when\fP field 
.SS "bool Job::operator== (const \fBJob\fP &other) const"

.PP
Compares equal all fields excpet \fBJob::when\fP\&. 
.SH "Member Data Documentation"
.PP 
.SS "string Job::arg0"

.PP
Task's first argument\&. 
.SS "string Job::arg1"

.PP
Task's second argument\&. 
.SS "string Job::arg2"

.PP
Task's third argument\&. Default constructor 
.SS "\fBISchedulable\fP* Job::subject"

.PP
Pointer to object being context of \fBJob\fP execution\&. 
.SS "\fBISchedulable::TaskID\fP Job::task"

.PP
ID of task\&. \fBSee Also:\fP
.RS 4
\fBISchedulable::TaskID\fP 
.RE
.PP

.SS "time_t Job::when"

.PP
Time when \fBJob\fP should be processed\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
