.TH "src/fuse/jobScheduler.cc" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fuse/jobScheduler.cc \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPTHREAD_CMD\fP(M)"
.br
.RI "\fIRun command M, fetch error code and if error occured restart daemon\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Rafal Slota 
.RE
.PP
\fBCopyright:\fP
.RS 4
(C) 2013 ACK CYFRONET AGH 
.PP
This software is released under the MIT license cited in 'LICENSE\&.txt' 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define PTHREAD_CMD(M)"
\fBValue:\fP
.PP
.nf
{ \
                            int e = M; \
                            if(e != 0) { \
                                LOG(ERROR) << 'Daemon mutex error: ' << e; \
                                startDaemon(); \
                                return; \
                            } \
                        }
.fi
.PP
Run command M, fetch error code and if error occured restart daemon\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
