.TH "include/fuse/jobScheduler.hh" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/fuse/jobScheduler.hh \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBJob\fP"
.br
.RI "\fIThe \fBJob\fP struct Used by \fBJobScheduler\fP to describe scheduled tasks\&. \fP"
.ti -1c
.RI "class \fBJobScheduler\fP"
.br
.RI "\fIThe \fBJobScheduler\fP class Objects of this class are living daemons (threads) with their own run queue from which they are precessing tasks\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Rafal Slota 
.RE
.PP
\fBCopyright:\fP
.RS 4
(C) 2013 ACK CYFRONET AGH 
.PP
This software is released under the MIT license cited in 'LICENSE\&.txt' 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
