.TH "veilprotocol/LICENSE.txt" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
veilprotocol/LICENSE.txt \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "MIT free of to any person 
.br
obtaining a \fBcopy\fP of this 
.br
software and associated 
.br
documentation \fBfiles\fP (the'Software')"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "MIT \fBLicense\fP"
.br
.ti -1c
.RI "MIT free of \fBcharge\fP"
.br
.ti -1c
.RI "MIT free of to any person 
.br
obtaining a \fBcopy\fP of this 
.br
software and associated 
.br
documentation to deal in the 
.br
\fBSoftware\fP without \fBrestriction\fP"
.br
.ti -1c
.RI "MIT free of to any person 
.br
obtaining a \fBcopy\fP of this 
.br
software and associated 
.br
documentation to deal in the 
.br
\fBSoftware\fP without including 
.br
without limitation the rights 
.br
to \fBuse\fP"
.br
.ti -1c
.RI "MIT free of to any person 
.br
obtaining a copy of this 
.br
software and associated 
.br
documentation to deal in the 
.br
\fBSoftware\fP without including 
.br
without limitation the rights 
.br
to \fBcopy\fP"
.br
.ti -1c
.RI "MIT free of to any person 
.br
obtaining a \fBcopy\fP of this 
.br
software and associated 
.br
documentation to deal in the 
.br
\fBSoftware\fP without including 
.br
without limitation the rights 
.br
to \fBmodify\fP"
.br
.ti -1c
.RI "MIT free of to any person 
.br
obtaining a \fBcopy\fP of this 
.br
software and associated 
.br
documentation to deal in the 
.br
\fBSoftware\fP without including 
.br
without limitation the rights 
.br
to \fBmerge\fP"
.br
.ti -1c
.RI "MIT free of to any person 
.br
obtaining a \fBcopy\fP of this 
.br
software and associated 
.br
documentation to deal in the 
.br
\fBSoftware\fP without including 
.br
without limitation the rights 
.br
to \fBpublish\fP"
.br
.ti -1c
.RI "MIT free of to any person 
.br
obtaining a \fBcopy\fP of this 
.br
software and associated 
.br
documentation to deal in the 
.br
\fBSoftware\fP without including 
.br
without limitation the rights 
.br
to \fBdistribute\fP"
.br
.ti -1c
.RI "MIT free of to any person 
.br
obtaining a \fBcopy\fP of this 
.br
software and associated 
.br
documentation to deal in the 
.br
\fBSoftware\fP without including 
.br
without limitation the rights 
.br
to \fBsublicense\fP"
.br
.ti -1c
.RI "MIT free of to any person 
.br
obtaining a \fBcopy\fP of this 
.br
software and associated 
.br
documentation to deal in the 
.br
Software without including 
.br
without limitation the rights 
.br
to and or sell copies of the \fBSoftware\fP"
.br
.ti -1c
.RI "MIT free of to any person 
.br
obtaining a \fBcopy\fP of this 
.br
software and associated 
.br
documentation to deal in the 
.br
\fBSoftware\fP without including 
.br
without limitation the rights 
.br
to and or sell copies of the 
.br
and to permit persons to whom 
.br
the \fBSoftware\fP is furnished to 
.br
do \fBso\fP"
.br
.ti -1c
.RI "MIT free of to any person 
.br
obtaining a \fBcopy\fP of this 
.br
software and associated 
.br
documentation to deal in the 
.br
\fBSoftware\fP without including 
.br
without limitation the rights 
.br
to and or sell copies of the 
.br
and to permit persons to whom 
.br
the \fBSoftware\fP is furnished to 
.br
do subject to the following \fBconditions\fP"
.br
.ti -1c
.RI "MIT free of to any person 
.br
obtaining a \fBcopy\fP of this 
.br
software and associated 
.br
documentation to deal in the 
.br
\fBSoftware\fP without including 
.br
without limitation the rights 
.br
to and or sell copies of the 
.br
and to permit persons to whom 
.br
the \fBSoftware\fP is furnished to 
.br
do subject to the following 
.br
WITHOUT WARRANTY OF ANY \fBKIND\fP"
.br
.ti -1c
.RI "MIT free of to any person 
.br
obtaining a \fBcopy\fP of this 
.br
software and associated 
.br
documentation to deal in the 
.br
\fBSoftware\fP without including 
.br
without limitation the rights 
.br
to and or sell copies of the 
.br
and to permit persons to whom 
.br
the \fBSoftware\fP is furnished to 
.br
do subject to the following 
.br
WITHOUT WARRANTY OF ANY 
.br
EXPRESS OR \fBIMPLIED\fP"
.br
.ti -1c
.RI "MIT free of to any person 
.br
obtaining a \fBcopy\fP of this 
.br
software and associated 
.br
documentation to deal in the 
.br
\fBSoftware\fP without including 
.br
without limitation the rights 
.br
to and or sell copies of the 
.br
and to permit persons to whom 
.br
the \fBSoftware\fP is furnished to 
.br
do subject to the following 
.br
WITHOUT WARRANTY OF ANY 
.br
EXPRESS OR INCLUDING BUT NOT 
.br
LIMITED TO THE WARRANTIES OF \fBMERCHANTABILITY\fP"
.br
.ti -1c
.RI "MIT free of to any person 
.br
obtaining a \fBcopy\fP of this 
.br
software and associated 
.br
documentation to deal in the 
.br
\fBSoftware\fP without including 
.br
without limitation the rights 
.br
to and or sell copies of the 
.br
and to permit persons to whom 
.br
the \fBSoftware\fP is furnished to 
.br
do subject to the following 
.br
WITHOUT WARRANTY OF ANY 
.br
EXPRESS OR INCLUDING BUT NOT 
.br
LIMITED TO THE WARRANTIES OF 
.br
FITNESS FOR A PARTICULAR 
.br
PURPOSE AND NONINFRINGEMENT IN 
.br
NO EVENT SHALL THE AUTHORS OR 
.br
COPYRIGHT HOLDERS BE LIABLE 
.br
FOR ANY \fBCLAIM\fP"
.br
.ti -1c
.RI "MIT free of to any person 
.br
obtaining a \fBcopy\fP of this 
.br
software and associated 
.br
documentation to deal in the 
.br
\fBSoftware\fP without including 
.br
without limitation the rights 
.br
to and or sell copies of the 
.br
and to permit persons to whom 
.br
the \fBSoftware\fP is furnished to 
.br
do subject to the following 
.br
WITHOUT WARRANTY OF ANY 
.br
EXPRESS OR INCLUDING BUT NOT 
.br
LIMITED TO THE WARRANTIES OF 
.br
FITNESS FOR A PARTICULAR 
.br
PURPOSE AND NONINFRINGEMENT IN 
.br
NO EVENT SHALL THE AUTHORS OR 
.br
COPYRIGHT HOLDERS BE LIABLE 
.br
FOR ANY DAMAGES OR OTHER \fBLIABILITY\fP"
.br
.ti -1c
.RI "MIT free of to any person 
.br
obtaining a \fBcopy\fP of this 
.br
software and associated 
.br
documentation to deal in the 
.br
\fBSoftware\fP without including 
.br
without limitation the rights 
.br
to and or sell copies of the 
.br
and to permit persons to whom 
.br
the \fBSoftware\fP is furnished to 
.br
do subject to the following 
.br
WITHOUT WARRANTY OF ANY 
.br
EXPRESS OR INCLUDING BUT NOT 
.br
LIMITED TO THE WARRANTIES OF 
.br
FITNESS FOR A PARTICULAR 
.br
PURPOSE AND NONINFRINGEMENT IN 
.br
NO EVENT SHALL THE AUTHORS OR 
.br
COPYRIGHT HOLDERS BE LIABLE 
.br
FOR ANY DAMAGES OR OTHER 
.br
WHETHER IN AN ACTION OF \fBCONTRACT\fP"
.br
.ti -1c
.RI "MIT free of to any person 
.br
obtaining a \fBcopy\fP of this 
.br
software and associated 
.br
documentation to deal in the 
.br
\fBSoftware\fP without including 
.br
without limitation the rights 
.br
to and or sell copies of the 
.br
and to permit persons to whom 
.br
the \fBSoftware\fP is furnished to 
.br
do subject to the following 
.br
WITHOUT WARRANTY OF ANY 
.br
EXPRESS OR INCLUDING BUT NOT 
.br
LIMITED TO THE WARRANTIES OF 
.br
FITNESS FOR A PARTICULAR 
.br
PURPOSE AND NONINFRINGEMENT IN 
.br
NO EVENT SHALL THE AUTHORS OR 
.br
COPYRIGHT HOLDERS BE LIABLE 
.br
FOR ANY DAMAGES OR OTHER 
.br
WHETHER IN AN ACTION OF TORT 
.br
OR \fBOTHERWISE\fP"
.br
.ti -1c
.RI "MIT free of to any person 
.br
obtaining a \fBcopy\fP of this 
.br
software and associated 
.br
documentation to deal in the 
.br
\fBSoftware\fP without including 
.br
without limitation the rights 
.br
to and or sell copies of the 
.br
and to permit persons to whom 
.br
the \fBSoftware\fP is furnished to 
.br
do subject to the following 
.br
WITHOUT WARRANTY OF ANY 
.br
EXPRESS OR INCLUDING BUT NOT 
.br
LIMITED TO THE WARRANTIES OF 
.br
FITNESS FOR A PARTICULAR 
.br
PURPOSE AND NONINFRINGEMENT IN 
.br
NO EVENT SHALL THE AUTHORS OR 
.br
COPYRIGHT HOLDERS BE LIABLE 
.br
FOR ANY DAMAGES OR OTHER 
.br
WHETHER IN AN ACTION OF TORT 
.br
OR ARISING \fBFROM\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "MIT free of to any person obtaining a \fBcopy\fP of this software and associated documentation files (the'Software')"

.SH "Variable Documentation"
.PP 
.SS "MIT free of charge"

.SS "MIT free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM"

.SS "MIT free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following conditions"

.SS "MIT free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER WHETHER IN AN ACTION OF CONTRACT"

.SS "MIT free of to any person obtaining a copy of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to copy"

.SS "MIT free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to distribute"

.SS "MIT free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER WHETHER IN AN ACTION OF TORT OR ARISING FROM"

.SS "MIT free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY EXPRESS OR IMPLIED"

.SS "MIT free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY KIND"

.SS "MIT free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY"

.SS "MIT License"

.SS "MIT free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY"

.SS "MIT free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to merge"

.SS "MIT free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to modify"

.SS "MIT free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do subject to the following WITHOUT WARRANTY OF ANY EXPRESS OR INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGES OR OTHER WHETHER IN AN ACTION OF TORT OR OTHERWISE"

.SS "MIT free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to publish"

.SS "MIT free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without restriction"

.SS "MIT free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to and or sell copies of the and to permit persons to whom the \fBSoftware\fP is furnished to do so"

.SS "MIT free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the Software without including without limitation the rights to and or sell copies of the Software"

.SS "MIT free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to sublicense"

.SS "MIT free of to any person obtaining a \fBcopy\fP of this software and associated documentation to deal in the \fBSoftware\fP without including without limitation the rights to use"

.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
