.TH "src/fuse/messageBuilder.cc" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fuse/messageBuilder.cc \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGET_FILE_LOCATION\fP   'getfilelocation'"
.br
.ti -1c
.RI "#define \fBFUSE_MESSAGE\fP   'fusemessage'"
.br
.ti -1c
.RI "#define \fBFSLOGIC\fP   'fslogic'"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Beata Skiba 
.RE
.PP
\fBCopyright:\fP
.RS 4
(C) 2013 ACK CYFRONET AGH 
.PP
This software is released under the MIT license cited in 'LICENSE\&.txt' 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define FSLOGIC   'fslogic'"

.SS "#define FUSE_MESSAGE   'fusemessage'"

.SS "#define GET_FILE_LOCATION   'getfilelocation'"

.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
