.TH "MessageBuilder" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MessageBuilder \- 
.PP
The \fBMessageBuilder\fP class\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessageBuilder\fP ()"
.br
.ti -1c
.RI "\fB~MessageBuilder\fP ()"
.br
.ti -1c
.RI "FuseMessage * \fBcreateFuseMessage\fP (string id, string messageType, string messageInput)"
.br
.ti -1c
.RI "ClusterMsg * \fBcreateClusterMessage\fP (string moduleName, string messageType, string answerType, string answerDecoderName, bool synch, string input)"
.br
.ti -1c
.RI "ClusterMsg * \fBcreateClusterMessage\fP (string moduleName, string messageType, string answerType, string answerDecoderName, bool synch)"
.br
.ti -1c
.RI "ClusterMsg * \fBpackFuseMessage\fP (string messageType, string answerType, string answerDecoderName, string messageInput)"
.br
.ti -1c
.RI "FuseMessage * \fBdecodeFuseAnswer\fP (Answer &answer)"
.br
.ti -1c
.RI "string \fBdecodeAtomAnswer\fP (Answer &answer)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBMessageBuilder\fP class\&. 

This class can be used to build protobuf messages used to communicate with cluster\&. Theres encode and decode method for each base message type used by VeilClient\&. Arguments matches proto specification of their messages\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MessageBuilder::MessageBuilder ()"

.SS "MessageBuilder::~MessageBuilder ()"

.SH "Member Function Documentation"
.PP 
.SS "ClusterMsg * MessageBuilder::createClusterMessage (stringmoduleName, stringmessageType, stringanswerType, stringanswerDecoderName, boolsynch, stringinput)"

.SS "ClusterMsg * MessageBuilder::createClusterMessage (stringmoduleName, stringmessageType, stringanswerType, stringanswerDecoderName, boolsynch)"

.SS "FuseMessage * MessageBuilder::createFuseMessage (stringid, stringmessageType, stringmessageInput)"

.SS "string MessageBuilder::decodeAtomAnswer (Answer &answer)"

.SS "FuseMessage * MessageBuilder::decodeFuseAnswer (Answer &answer)"

.SS "ClusterMsg * MessageBuilder::packFuseMessage (stringmessageType, stringanswerType, stringanswerDecoderName, stringmessageInput)"


.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
