.TH "include/fuse/messageBuilder.hh" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/fuse/messageBuilder.hh \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMessageBuilder\fP"
.br
.RI "\fIThe \fBMessageBuilder\fP class\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFUSE_MESSAGES\fP   'fuse_messages'"
.br
.ti -1c
.RI "#define \fBCOMMUNICATION_PROTOCOL\fP   'communication_protocol'"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Beata Skiba 
.RE
.PP
\fBCopyright:\fP
.RS 4
(C) 2013 ACK CYFRONET AGH 
.PP
This software is released under the MIT license cited in 'LICENSE\&.txt' 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define COMMUNICATION_PROTOCOL   'communication_protocol'"

.SS "#define FUSE_MESSAGES   'fuse_messages'"

.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
