.TH "src/fuse/metaCache.cc" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fuse/metaCache.cc \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Rafal Slota 
.RE
.PP
\fBCopyright:\fP
.RS 4
(C) 2013 ACK CYFRONET AGH 
.PP
This software is released under the MIT license cited in 'LICENSE\&.txt' 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
