.TH "MetaCache" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MetaCache \- 
.PP
Class responsible for caching file attributes\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBISchedulable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMetaCache\fP ()"
.br
.ti -1c
.RI "\fB~MetaCache\fP ()"
.br
.ti -1c
.RI "void \fBaddAttr\fP (string, struct stat)"
.br
.RI "\fICache given attributes Expiration time can be set using configuration file\&. \fP"
.ti -1c
.RI "void \fBclearAttrs\fP ()"
.br
.RI "\fIClear whole cache\&. \fP"
.ti -1c
.RI "bool \fBgetAttr\fP (string, struct stat *)"
.br
.RI "\fIGets file attributes from cache\&. \fP"
.ti -1c
.RI "void \fBclearAttr\fP (string path)"
.br
.RI "\fIRemove cache for given file\&. \fP"
.ti -1c
.RI "bool \fBrunTask\fP (\fBTaskID\fP taskId, string arg0, string arg1, string arg3)"
.br
.RI "\fITask runner derived from \fBISchedulable\fP\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "map< string, pair< time_t, 
.br
struct stat > > \fBm_statMap\fP"
.br
.RI "\fIThis is the cache map\&. \fP"
.ti -1c
.RI "\fBReadWriteLock\fP \fBm_statMapLock\fP"
.br
.RI "\fILock used to synchronize access to \fBMetaCache::m_statMap\fP\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Class responsible for caching file attributes\&. 

\fBSee Also:\fP
.RS 4
\fBVeilFS::getattr\fP 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "MetaCache::MetaCache ()"

.SS "MetaCache::~MetaCache ()"

.SH "Member Function Documentation"
.PP 
.SS "void MetaCache::addAttr (stringpath, struct statattr)"

.PP
Cache given attributes Expiration time can be set using configuration file\&. 
.SS "void MetaCache::clearAttr (stringpath)"

.PP
Remove cache for given file\&. 
.SS "void MetaCache::clearAttrs ()"

.PP
Clear whole cache\&. 
.SS "bool MetaCache::getAttr (stringpath, struct stat *attr)"

.PP
Gets file attributes from cache\&. \fBParameters:\fP
.RS 4
\fIstat\fP Pointer to stat structure that should be filled with data from cache 
.RE
.PP
\fBReturns:\fP
.RS 4
Bool saying if operation succeed and stat struct was filled with data 
.RE
.PP

.SS "bool MetaCache::runTask (\fBTaskID\fPtaskId, stringarg0, stringarg1, stringarg3)\fC [virtual]\fP"

.PP
Task runner derived from \fBISchedulable\fP\&. \fBSee Also:\fP
.RS 4
\fBISchedulable::runTask\fP 
.RE
.PP

.PP
Implements \fBISchedulable\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "map<string, pair<time_t, struct stat> > MetaCache::m_statMap\fC [private]\fP"

.PP
This is the cache map\&. Value of this map is pair containing expiration time of attributes and stat struct itself 
.SS "\fBReadWriteLock\fP MetaCache::m_statMapLock\fC [private]\fP"

.PP
Lock used to synchronize access to \fBMetaCache::m_statMap\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
