.TH "include/fuse/metaCache.hh" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/fuse/metaCache.hh \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMetaCache\fP"
.br
.RI "\fIClass responsible for caching file attributes\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBATTR_DEFAULT_EXPIRATION_TIME\fP   60"
.br
.RI "\fIDefault expiration time for file attribute cache (can be overriden by config) \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Rafal Slota 
.RE
.PP
\fBCopyright:\fP
.RS 4
(C) 2013 ACK CYFRONET AGH 
.PP
This software is released under the MIT license cited in 'LICENSE\&.txt' 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define ATTR_DEFAULT_EXPIRATION_TIME   60"

.PP
Default expiration time for file attribute cache (can be overriden by config) 
.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
