.TH "StorageHelperFactory" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StorageHelperFactory \- 
.PP
Singleton Factory providing objects of requested storage helpers\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~StorageHelperFactory\fP ()"
.br
.ti -1c
.RI "std::shared_ptr< \fBIStorageHelper\fP > \fBgetStorageHelper\fP (std::string, std::string)"
.br
.ti -1c
.RI "\fB~StorageHelperFactory\fP ()"
.br
.ti -1c
.RI "\fBIStorageHelper\fP * \fBgetStorageHelper\fP (std::string sh, std::vector< std::string > args)"
.br
.RI "\fIProduces storage helper object\&. \fP"
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBStorageHelperFactory\fP * \fBinstance\fP ()"
.br
.ti -1c
.RI "static \fBStorageHelperFactory\fP * \fBinstance\fP ()"
.br
.RI "\fISingleton instance getter\&. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBStorageHelperFactory\fP ()"
.br
.ti -1c
.RI "\fBStorageHelperFactory\fP ()"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static \fBStorageHelperFactory\fP * \fB_instance\fP = NULL"
.br
.RI "\fISingleton instance\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Singleton Factory providing objects of requested storage helpers\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StorageHelperFactory::StorageHelperFactory ()\fC [private]\fP"

.SS "StorageHelperFactory::~StorageHelperFactory ()"

.SS "StorageHelperFactory::StorageHelperFactory ()\fC [private]\fP"

.SS "StorageHelperFactory::~StorageHelperFactory ()"

.SH "Member Function Documentation"
.PP 
.SS "std::shared_ptr<\fBIStorageHelper\fP> StorageHelperFactory::getStorageHelper (std::string, std::string)"

.SS "\fBIStorageHelper\fP * StorageHelperFactory::getStorageHelper (std::stringsh, std::vector< std::string >args)"

.PP
Produces storage helper object\&. \fBParameters:\fP
.RS 4
\fIsh\fP Name of storage helper that has to be returned\&. 
.br
\fIargs\fP Arguments vector passed as argument to storge helper's constructor\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Pointer to storage helper object along with its ownership\&. 
.RE
.PP

.SS "\fBStorageHelperFactory\fP * StorageHelperFactory::instance ()\fC [static]\fP"

.SS "static \fBStorageHelperFactory\fP* StorageHelperFactory::instance ()\fC [static]\fP"

.PP
Singleton instance getter\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBStorageHelperFactory\fP * StorageHelperFactory::_instance = NULL\fC [static]\fP, \fC [private]\fP"

.PP
Singleton instance\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
