.TH "include/fuse/storageMapper.hh" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/fuse/storageMapper.hh \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBlocationInfo\fP"
.br
.RI "\fIStructure containing file mapping base information\&. \fP"
.ti -1c
.RI "struct \fBstorageInfo\fP"
.br
.ti -1c
.RI "class \fBStorageMapper\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBlocationInfo\fP \fBlocationInfo\fP"
.br
.RI "\fIStructure containing file mapping base information\&. \fP"
.ti -1c
.RI "typedef struct \fBstorageInfo\fP \fBstorageInfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Beata Skiba 
.PP
Rafal Slota 
.RE
.PP
\fBCopyright:\fP
.RS 4
(C) 2013 ACK CYFRONET AGH 
.PP
This software is released under the MIT license cited in 'LICENSE\&.txt' 
.RE
.PP

.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBlocationInfo\fP  \fBlocationInfo\fP"

.PP
Structure containing file mapping base information\&. 
.SS "typedef struct \fBstorageInfo\fP  \fBstorageInfo\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
