.TH "storageInfo" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
storageInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBisValid\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "time_t \fBlast_updated\fP"
.br
.RI "\fILast update time\&. \fP"
.ti -1c
.RI "string \fBstorageHelperName\fP"
.br
.RI "\fIName of storage helper\&. \fP"
.ti -1c
.RI "vector< string > \fBstorageHelperArgs\fP"
.br
.RI "\fIArguments for storage helper\&. \fP"
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool storageInfo::isValid ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "time_t storageInfo::last_updated"

.PP
Last update time\&. 
.SS "vector<string> storageInfo::storageHelperArgs"

.PP
Arguments for storage helper\&. \fBSee Also:\fP
.RS 4
\fBStorageHelperFactory::getStorageHelper\fP 
.RE
.PP

.SS "string storageInfo::storageHelperName"

.PP
Name of storage helper\&. \fBSee Also:\fP
.RS 4
\fBStorageHelperFactory::getStorageHelper\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
