.TH "VeilException" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VeilException \- 
.PP
Base class of all VeilClient exceptions\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits std::exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVeilException\fP ()"
.br
.RI "\fIDefault, empty constuctor\&. \fP"
.ti -1c
.RI "\fBVeilException\fP (std::string \fBveilError\fP, std::string logMsg='')"
.br
.RI "\fI\fBVeilException\fP main constructor\&. \fP"
.ti -1c
.RI "virtual \fB~VeilException\fP ()  throw ()"
.br
.ti -1c
.RI "const char * \fBwhat\fP () const   throw ()"
.br
.RI "\fIReturns \fBVeilException::m_logMessage\fP\&. \fP"
.ti -1c
.RI "std::string \fBveilError\fP () const "
.br
.RI "\fIReturns \fBVeilException::m_veilError\fP\&. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBm_logMessage\fP"
.br
.RI "\fIHuman readable excpetion reason message\&. \fP"
.ti -1c
.RI "std::string \fBm_veilError\fP"
.br
.RI "\fIPOSIX error name\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Base class of all VeilClient exceptions\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "VeilException::VeilException ()"

.PP
Default, empty constuctor\&. 
.SS "VeilException::VeilException (std::stringveilError, std::stringlogMsg = \fC''\fP)"

.PP
\fBVeilException\fP main constructor\&. \fBParameters:\fP
.RS 4
\fIveilError\fP POSIX error name\&. Should be compatibile with \fBVeilFS::translateError\fP 
.br
\fIlogMsg\fP Human readable excpetion reason message\&. 
.RE
.PP
\fBSee Also:\fP
.RS 4
\fBVeilFS::translateError\fP 
.RE
.PP

.SS "VeilException::~VeilException ()  throw ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "std::string VeilException::veilError () const"

.PP
Returns \fBVeilException::m_veilError\fP\&. 
.SS "const char * VeilException::what () const  throw ()"

.PP
Returns \fBVeilException::m_logMessage\fP\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::string VeilException::m_logMessage\fC [private]\fP"

.PP
Human readable excpetion reason message\&. 
.SS "std::string VeilException::m_veilError\fC [private]\fP"

.PP
POSIX error name\&. This error string should be compatibile with \fBVeilFS::translateError\fP\&.
.PP
\fBSee Also:\fP
.RS 4
\fBVeilFS::translateError\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
