.TH "include/fuse/veilException.hh" 3 "Wed Jul 31 2013" "VeilClient" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/fuse/veilException.hh \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVeilException\fP"
.br
.RI "\fIBase class of all VeilClient exceptions\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VeilClient from the source code\&.
